workflows:
  ios-build:
    name: iOS Build (Expo Prebuild)

    environment:
      groups:
        - appstore_credentials # <-- Este grupo debe contener APP_STORE_CONNECT_ISSUER_ID, KEY_IDENTIFIER, PRIVATE_KEY
      vars:
        NODE_VERSION: "18"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --clean --platform ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # La firma se asigna automáticamente, no necesitas manipular manualmente los certificados/perfiles

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace ios/PueblosBonitosApp.xcworkspace \
            -scheme PueblosBonitosApp \
            -archivePath build/PueblosBonitosApp.xcarchive \
            -configuration Release \
            -sdk iphoneos \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/PueblosBonitosApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    code_signing:
      distribution_type: app_store # O 'ad_hoc' según necesidad
      bundle_identifier: com.tuempresa.pueblosbonitos # <-- Exacto al de tu app

    publishing:
      app_store_connect: {} # Así está perfecto, sin apple_id ni password
