workflows:
  ios-build:
    name: iOS Build (Expo Prebuild)
    environment:
      vars:
        NODE_VERSION: "18"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --clean --platform ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace ios/PueblosBonitosApp.xcworkspace \
            -scheme PueblosBonitosApp \
            -archivePath build/PueblosBonitosApp.xcarchive \
            -configuration Release \
            -sdk iphoneos \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/PueblosBonitosApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
        ipa_path: "build/PueblosBonitosApp.ipa"
